del /q bin\*.exe
del /q bin\*.pdb
del /q bin\*.ilk
del /q doc\FoundationAPI\examples\*.exe
del /q doc\FoundationAPI\examples\*.ilk
del /q doc\FoundationAPI\examples\*.obj
del /q doc\FoundationAPI\examples\*.out
del /q doc\FoundationAPI\examples\*.pdb
del /q doc\FoundationAPI\examples\*.idb
del /q doc\FoundationAPI\examples\*.xml
del /q doc\FoundationAPI\examples\*._e57
del /q doc\FoundationAPI\html\*.*
del /q doc\FoundationAPI\html\search\*.*
del /q doc\FoundationAPI\latex\*.*
del /q lib\*.obj
del /q lib\*.lib
del /q lib\*.o
del /q src\examples\*.exe
del /q src\examples\*.obj
del /q src\examples\*.pdb
del /q src\examples\*.idb
del /q src\examples\*.ilk
del /q src\LASReader\*.exe
del /q src\LASReader\*.obj
del /q src\LASReader\*.pdb
del /q src\LASReader\*.idb
del /q src\LASReader\*.ilk
del /q src\RefImpl\*.exe
del /q src\RefImpl\*.obj
del /q src\RefImpl\*.pdb
del /q src\RefImpl\*.idb
del /q src\RefImpl\*.ilk
del /q src\time_conversion\*.exe
del /q src\time_conversion\*.obj
del /q src\time_conversion\*.pdb
del /q src\time_conversion\*.idb
del /q src\time_conversion\*.ilk
del /q src\tools\*.exe
del /q src\tools\*.obj
del /q src\tools\*.pdb
del /q src\tools\*.idb
del /q src\tools\*.ilk
