/*
 * stdint.h - stub version of general integer type decls.
 *
 * Copyright 2009 - 2010 Kevin Ackley (kackley@gwi.net)
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
#ifndef STDINT_H_INCLUDED
#define STDINT_H_INCLUDED

#include <boost/cstdint.hpp>    // for int8_t, int16_t, int32_t, etc...
using boost::int8_t;
using boost::uint8_t;
using boost::int16_t;
using boost::uint16_t;
using boost::int32_t;
using boost::uint32_t;
using boost::int64_t;
using boost::uint64_t;

#ifndef BOOST_HAS_STDINT_H
// If compiler doesn't have stdint.h, define these MIN/MAX constants:

// Minimum and maximum values for integers
#define INT8_MIN        (-128)
#define INT8_MAX        (127)
#define INT16_MIN       (-32767-1)
#define INT16_MAX       (32767)
#define INT32_MIN       (-2147483647-1)
#define INT32_MAX       (2147483647)
#define INT64_MIN       (static_cast<int64_t>(-9223372036854775808LL))
#define INT64_MAX       (static_cast<int64_t>(9223372036854775807LL))
#define UINT8_MIN       (0)
#define UINT8_MAX       (255)
#define UINT16_MIN      (0)
#define UINT16_MAX      (65535)
#define UINT32_MIN      (0)
#define UINT32_MAX      (4294967295U)
#define UINT64_MIN      (0LL)
#define UINT64_MAX      (18446744073709551615LL)
#endif

#include <float.h>  //??? not really integer stuff

//??? where should these go?
#define FLOAT_MIN (-FLT_MAX)
#define FLOAT_MAX FLT_MAX
#define DOUBLE_MIN (-DBL_MAX)
#define DOUBLE_MAX DBL_MAX

#endif
