# $Id$

# Copyright 2010 Roland Schwarz, Riegl LMS GmbH
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

if (Xerces3_INCLUDE_DIR)
    set (Xerces3_FIND_QUIETLY TRUE)
endif (Xerces3_INCLUDE_DIR)

find_path(Xerces3_INCLUDE_DIR
    xercesc/sax2/SAX2XMLReader.hpp
    ${XERCES_ROOT}/include
)

if (Xerces3_USE_STATIC_LIBS)
    find_library(Xerces3_LIBRARY_DEBUG
        xerces-c_static_3D.lib ${XERCES_ROOT}/lib
    )

    find_library(Xerces3_LIBRARY_RELEASE
        xerces-c_static_3.lib ${XERCES_ROOT}/lib
    )
else(Xerces3_USE_STATIC_LIBS)
    find_library(Xerces3_LIBRARY_DEBUG
        xerces-c_3D.lib ${XERCES_ROOT}/lib
    )

    find_library(Xerces3_LIBRARY_RELEASE
        xerces-c_3.lib ${XERCES_ROOT}/lib
    )
endif(Xerces3_USE_STATIC_LIBS)

mark_as_advanced(
    Xerces3_INCLUDE_DIR
    Xerces3_LIBRARY_DEBUG
    Xerces3_LIBRARY_RELEASE
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
    Xerces3
    "Unable to find Xerces3: \nPlease set the XERCES_ROOT variable to the Xerces directory.\n"
    Xerces3_INCLUDE_DIR
    Xerces3_LIBRARY_DEBUG
    Xerces3_LIBRARY_RELEASE
)

set(Xerces3_FOUND ${XERCES3_FOUND})
